name: flutter_core
description: "Flutter package containing my personal design system"
version: 1.0.0
homepage: TBA

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

flutter: